//! Turning profiles into files on disk — and showing exactly what that would
//! do before it happens.
//!
//! [`preview`] and [`apply`] build the same plan; apply is preview plus the
//! writes. Nothing in the app writes a config file by any other route.

use crate::error::{IoCtx, Result};
use crate::fsx;
use crate::gitcfg;
use crate::model::{validate_alias, Profile};
use crate::paths;
use crate::sshcfg;
use serde::Serialize;
use std::path::{Path, PathBuf};

const GENERATED_MARKER: &str = "# Generated by Git Switcher";

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FileChange {
    pub path: String,
    pub label: String,
    pub before: String,
    pub after: String,
    pub changed: bool,
    pub exists: bool,
    /// Set when this file is left over from a profile that no longer exists.
    pub orphan: bool,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PlanNote {
    /// "info" | "warn"
    pub level: String,
    pub message: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Plan {
    pub changes: Vec<FileChange>,
    pub has_changes: bool,
    /// Things worth saying before the user commits to the write.
    pub notes: Vec<PlanNote>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ApplyReport {
    pub written: Vec<String>,
    pub removed: Vec<String>,
    pub backups: Vec<String>,
}

struct PlannedWrite {
    path: PathBuf,
    contents: String,
    mode: u32,
}

struct FullPlan {
    changes: Vec<FileChange>,
    writes: Vec<PlannedWrite>,
    removals: Vec<PathBuf>,
    notes: Vec<PlanNote>,
}

fn change(path: &Path, label: &str, before: String, after: String) -> FileChange {
    FileChange {
        path: paths::contract(path),
        label: label.to_string(),
        changed: before != after,
        exists: path.exists(),
        before,
        after,
        orphan: false,
    }
}

/// `~/.gitconfig-*` files we generated for profiles that have since been
/// deleted or renamed. Only files carrying our header are candidates — a
/// hand-written `~/.gitconfig-whatever` is left alone.
fn orphan_includes(profiles: &[Profile]) -> Result<Vec<PathBuf>> {
    let home = paths::home()?;
    let live: Vec<String> = profiles
        .iter()
        .map(|p| format!(".gitconfig-{}", p.alias))
        .collect();

    let mut orphans = Vec::new();
    let entries = match std::fs::read_dir(&home) {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(orphans),
        Err(e) => return Err(e).ctx(format!("listing {}", home.display())),
    };

    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        let Some(suffix) = name.strip_prefix(".gitconfig-") else {
            continue;
        };
        // The suffix has to be a name we could actually have generated, not
        // merely start the right way. `validate_alias` rejects anything holding
        // a dot, which is what keeps our own `.gitconfig-work.bak` from being
        // mistaken for an orphan — it carries our header, so the content check
        // below waves it straight through. Deleting it backed it up again to
        // `.bak.bak`, and every later apply added one more level.
        if !validate_alias(suffix).is_ok_and(|valid| valid == suffix) {
            continue;
        }
        if live.contains(&name) {
            continue;
        }
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if fsx::read_opt(&path)?
            .is_some_and(|content| content.starts_with(GENERATED_MARKER))
        {
            orphans.push(path);
        }
    }
    orphans.sort();
    Ok(orphans)
}

fn build(profiles: &[Profile], global: Option<&Profile>) -> Result<FullPlan> {
    let mut changes = Vec::new();
    let mut writes = Vec::new();
    let mut notes = Vec::new();

    let (ssh_path, ssh_before, ssh_after) = sshcfg::render_file(profiles)?;
    changes.push(change(
        &ssh_path,
        "SSH host aliases",
        ssh_before.clone(),
        ssh_after.clone(),
    ));
    if ssh_before != ssh_after {
        writes.push(PlannedWrite {
            path: ssh_path,
            contents: ssh_after,
            mode: 0o600,
        });
    }

    let (git_path, git_before, git_after) = gitcfg::render_file(profiles, global)?;

    if let Some(profile) = global {
        // Git takes the last assignment wins, so where the user's own [user]
        // section sits decides whether our global identity actually applies.
        match gitcfg::locate_user_section(&git_before) {
            gitcfg::UserSection::AfterBlock => notes.push(PlanNote {
                level: "warn".to_string(),
                message: format!(
                    "Your ~/.gitconfig sets user.name/user.email below the managed block, so that section wins and \"{}\" will not take effect globally. Move it above the block, or remove it.",
                    profile.alias
                ),
            }),
            gitcfg::UserSection::BeforeBlock => notes.push(PlanNote {
                level: "info".to_string(),
                message: format!(
                    "Your ~/.gitconfig already has its own [user] section. It stays in the file, but \"{}\" is written after it and so takes precedence.",
                    profile.alias
                ),
            }),
            gitcfg::UserSection::None => {}
        }
    }
    changes.push(change(
        &git_path,
        "Global git config (includeIf)",
        git_before.clone(),
        git_after.clone(),
    ));
    if git_before != git_after {
        writes.push(PlannedWrite {
            path: git_path,
            contents: git_after,
            mode: 0o644,
        });
    }

    for profile in profiles {
        let path = paths::include_path(&profile.alias)?;
        let before = fsx::read_or_empty(&path)?;
        let after = gitcfg::render_include_file(profile)?;
        changes.push(change(
            &path,
            &format!("Identity for \"{}\"", profile.alias),
            before.clone(),
            after.clone(),
        ));
        if before != after {
            writes.push(PlannedWrite {
                path,
                contents: after,
                mode: 0o644,
            });
        }
    }

    let removals = orphan_includes(profiles)?;
    for path in &removals {
        let before = fsx::read_or_empty(path)?;
        changes.push(FileChange {
            path: paths::contract(path),
            label: "Left over from a deleted profile".to_string(),
            changed: true,
            exists: true,
            before,
            after: String::new(),
            orphan: true,
        });
    }

    Ok(FullPlan {
        changes,
        writes,
        removals,
        notes,
    })
}

pub fn preview(profiles: &[Profile], global: Option<&Profile>) -> Result<Plan> {
    let plan = build(profiles, global)?;
    let has_changes = plan.changes.iter().any(|c| c.changed);
    Ok(Plan {
        changes: plan.changes,
        has_changes,
        notes: plan.notes,
    })
}

pub fn apply(profiles: &[Profile], global: Option<&Profile>) -> Result<ApplyReport> {
    let plan = build(profiles, global)?;
    let mut report = ApplyReport {
        written: Vec::new(),
        removed: Vec::new(),
        backups: Vec::new(),
    };

    // Make sure ~/.ssh exists with sane permissions before writing into it;
    // ssh refuses to use a world-readable directory.
    fsx::ensure_dir(&paths::ssh_dir()?, 0o700)?;

    for write in plan.writes {
        if let Some(backup) = fsx::write_atomic(&write.path, &write.contents, write.mode)? {
            report.backups.push(paths::contract(&backup));
        }
        report.written.push(paths::contract(&write.path));
    }

    for path in plan.removals {
        // Keep a copy even on delete — this is still the user's file.
        if let Some(backup) = fsx::backup(&path)? {
            report.backups.push(paths::contract(&backup));
        }
        std::fs::remove_file(&path).ctx(format!("removing {}", path.display()))?;
        report.removed.push(paths::contract(&path));
    }

    Ok(report)
}
