//! Safe editing of config files the user already owns.
//!
//! Two rules hold everywhere in this module:
//!   1. Never write in place — write a sibling temp file and rename, so an
//!      interrupted run can't leave a half-written `~/.ssh/config`.
//!   2. Never overwrite without first copying the previous contents to `.bak`.

use crate::error::{IoCtx, Result};
use std::fs;
use std::io::Write;
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};

pub const BEGIN: &str = "# >>> gitswitcher managed block >>>";
pub const END: &str = "# <<< gitswitcher managed block <<<";
pub const WARNING: &str = "# Everything between these markers is regenerated by Git Switcher.\n# Edits inside the block will be lost; edit your profiles in the app instead.";

pub fn read_opt(path: &Path) -> Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(s) => Ok(Some(s)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(e).ctx(format!("reading {}", path.display())),
    }
}

pub fn read_or_empty(path: &Path) -> Result<String> {
    Ok(read_opt(path)?.unwrap_or_default())
}

pub fn ensure_dir(path: &Path, mode: u32) -> Result<()> {
    if !path.exists() {
        fs::create_dir_all(path).ctx(format!("creating {}", path.display()))?;
        fs::set_permissions(path, fs::Permissions::from_mode(mode))
            .ctx(format!("setting permissions on {}", path.display()))?;
    }
    Ok(())
}

/// Copy `path` to `path.bak` before we replace it. Returns the backup path,
/// or `None` when there was nothing there to lose.
pub fn backup(path: &Path) -> Result<Option<PathBuf>> {
    if !path.exists() {
        return Ok(None);
    }
    let mut name = path.as_os_str().to_os_string();
    name.push(".bak");
    let backup = PathBuf::from(name);
    fs::copy(path, &backup).ctx(format!("backing up {}", path.display()))?;
    Ok(Some(backup))
}

/// Write `contents` to `path` atomically, backing up any existing file first.
/// Returns the backup path when one was made.
pub fn write_atomic(path: &Path, contents: &str, mode: u32) -> Result<Option<PathBuf>> {
    if let Some(parent) = path.parent() {
        ensure_dir(parent, 0o700)?;
    }
    let backup = backup(path)?;

    let tmp = path.with_extension(format!(
        "gitswitcher-tmp-{}",
        std::process::id()
    ));
    {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(mode)
            .open(&tmp)
            .ctx(format!("opening {}", tmp.display()))?;
        file.write_all(contents.as_bytes())
            .ctx(format!("writing {}", tmp.display()))?;
        file.sync_all().ctx(format!("flushing {}", tmp.display()))?;
    }
    // Permissions are only applied by `.mode()` on creation, so re-assert them
    // in case the temp file already existed from a previous crashed run.
    fs::set_permissions(&tmp, fs::Permissions::from_mode(mode))
        .ctx(format!("setting permissions on {}", tmp.display()))?;
    fs::rename(&tmp, path).ctx(format!("replacing {}", path.display()))?;
    Ok(backup)
}

/// Remove our managed block from `content`, leaving everything the user wrote
/// themselves untouched.
pub fn strip_block(content: &str) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let begin = lines.iter().position(|l| l.trim() == BEGIN);
    let end = lines.iter().position(|l| l.trim() == END);

    let (Some(begin), Some(end)) = (begin, end) else {
        return content.to_string();
    };
    if end < begin {
        return content.to_string();
    }

    let mut kept: Vec<&str> = Vec::with_capacity(lines.len());
    kept.extend_from_slice(&lines[..begin]);
    kept.extend_from_slice(&lines[end + 1..]);

    // Collapse the blank lines that used to surround the block.
    while kept.last().is_some_and(|l| l.trim().is_empty()) {
        kept.pop();
    }
    let mut out = kept.join("\n");
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

/// Replace our managed block in place, or append it if there isn't one yet.
///
/// `body` is the block's inner content, without the markers. Passing an empty
/// body removes the block entirely — that's how the last profile disappearing
/// cleans up after itself.
pub fn upsert_block(content: &str, body: &str) -> String {
    let stripped = strip_block(content);
    let body = body.trim_end();
    if body.is_empty() {
        return stripped;
    }

    let block = format!("{BEGIN}\n{WARNING}\n{body}\n{END}\n");
    if stripped.trim().is_empty() {
        return block;
    }
    format!("{}\n\n{block}", stripped.trim_end())
}

/// Escape a value for the right-hand side of a `key = "value"` line in a git
/// config file.
pub fn git_quote(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// ssh_config(5) only needs quoting when a value contains whitespace.
pub fn ssh_quote(value: &str) -> String {
    if value.chars().any(char::is_whitespace) {
        format!("\"{}\"", value.replace('"', "\\\""))
    } else {
        value.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn upsert_appends_when_no_block_exists() {
        let existing = "Host example.com\n    User me\n";
        let result = upsert_block(existing, "Host work\n    User git\n");
        assert!(result.starts_with("Host example.com"));
        assert!(result.contains(BEGIN));
        assert!(result.contains("Host work"));
        assert!(result.trim_end().ends_with(END));
    }

    #[test]
    fn upsert_replaces_an_existing_block_and_is_idempotent() {
        let base = "# mine\nHost example.com\n";
        let once = upsert_block(base, "Host a\n");
        let twice = upsert_block(&once, "Host a\n");
        assert_eq!(once, twice, "applying twice must not append a second block");

        let changed = upsert_block(&once, "Host b\n");
        assert!(changed.contains("Host b"));
        assert!(!changed.contains("Host a"));
        assert_eq!(changed.matches(BEGIN).count(), 1);
    }

    #[test]
    fn user_content_around_the_block_survives() {
        let base = "# top matter\nHost keep-me\n";
        let with_block = upsert_block(base, "Host generated\n");
        let appended = format!("{with_block}\nHost added-later\n");

        let updated = upsert_block(&appended, "Host regenerated\n");
        assert!(updated.contains("Host keep-me"));
        assert!(updated.contains("Host added-later"));
        assert!(updated.contains("Host regenerated"));
        assert!(!updated.contains("Host generated\n"));
    }

    #[test]
    fn empty_body_removes_the_block_entirely() {
        let base = "Host keep-me\n";
        let with_block = upsert_block(base, "Host generated\n");
        let cleaned = upsert_block(&with_block, "");
        assert!(!cleaned.contains(BEGIN));
        assert!(cleaned.contains("Host keep-me"));
    }

    #[test]
    fn strip_is_a_no_op_without_markers() {
        let base = "Host example.com\n    User me\n";
        assert_eq!(strip_block(base), base);
    }

    #[test]
    fn git_quote_escapes_quotes_and_backslashes() {
        assert_eq!(git_quote(r#"A "B" \C"#), r#""A \"B\" \\C""#);
    }

    #[test]
    fn ssh_quote_only_quotes_when_needed() {
        assert_eq!(ssh_quote("~/.ssh/id_ed25519"), "~/.ssh/id_ed25519");
        assert_eq!(ssh_quote("~/my keys/id"), "\"~/my keys/id\"");
    }
}
