//! Generates the git side of the setup:
//!
//!   * `~/.gitconfig-<alias>` — one file per profile, owned entirely by the
//!     app and rewritten wholesale on apply;
//!   * a managed block in `~/.gitconfig` holding the `includeIf` lines that
//!     point at those files.

use crate::error::Result;
use crate::fsx;
use crate::model::Profile;
use crate::paths;
use std::path::PathBuf;

/// Contents of `~/.gitconfig-<alias>`.
pub fn render_include_file(profile: &Profile) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Git Switcher — do not edit.\n");
    out.push_str(&format!(
        "# Profile \"{}\". Change it in the app and apply again.\n\n",
        profile.alias
    ));
    out.push_str("[user]\n");
    out.push_str(&format!("\tname = {}\n", fsx::git_quote(&profile.name)));
    out.push_str(&format!("\temail = {}\n", fsx::git_quote(&profile.email)));
    out.push_str("\n[core]\n");
    // Pins the key even for repos whose remote uses a plain host rather than
    // the SSH alias, so an includeIf folder is self-sufficient.
    out.push_str(&format!(
        "\tsshCommand = {}\n",
        fsx::git_quote(&format!(
            "ssh -i {} -o IdentitiesOnly=yes",
            &profile.ssh_key_path
        ))
    ));
    out
}

/// `gitdir:` patterns need a trailing slash to match a directory and its
/// descendants rather than only an exact path.
fn gitdir_pattern(dir: &str) -> String {
    if dir.ends_with('/') {
        dir.to_string()
    } else {
        format!("{dir}/")
    }
}

/// The `includeIf` block for `~/.gitconfig`.
///
/// Git applies includes in file order and the last assignment wins, so shorter
/// (less specific) paths are emitted first: `~/code/` then `~/code/client-x/`
/// means the nested folder overrides its parent, which is what people expect.
pub fn render_block(profiles: &[Profile]) -> String {
    let mut entries: Vec<(String, String)> = Vec::new();
    for profile in profiles {
        for dir in &profile.dirs {
            entries.push((gitdir_pattern(dir), profile.alias.clone()));
        }
    }
    entries.sort_by(|a, b| a.0.len().cmp(&b.0.len()).then_with(|| a.0.cmp(&b.0)));

    let mut out = String::new();
    for (pattern, alias) in entries {
        out.push_str(&format!("[includeIf {}]\n", fsx::git_quote(&format!("gitdir:{pattern}"))));
        out.push_str(&format!("\tpath = ~/.gitconfig-{alias}\n"));
    }
    out
}

/// The full `~/.gitconfig` we would write, given what's on disk right now.
pub fn render_file(profiles: &[Profile]) -> Result<(PathBuf, String, String)> {
    let path = paths::gitconfig_path()?;
    let before = fsx::read_or_empty(&path)?;
    let after = fsx::upsert_block(&before, &render_block(profiles));
    Ok((path, before, after))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::now_iso;

    fn profile(alias: &str, dirs: &[&str]) -> Profile {
        Profile {
            id: alias.into(),
            alias: alias.into(),
            name: format!("{alias} user"),
            email: format!("{alias}@example.com"),
            host_name: "github.com".into(),
            host_alias: format!("github.com-{alias}"),
            ssh_key_path: format!("~/.ssh/id_{alias}"),
            dirs: dirs.iter().map(|d| d.to_string()).collect(),
            created_at: now_iso(),
            updated_at: now_iso(),
        }
    }

    #[test]
    fn gitdir_patterns_get_a_trailing_slash() {
        let block = render_block(&[profile("work", &["~/code/work"])]);
        assert!(block.contains(r#"[includeIf "gitdir:~/code/work/"]"#));
        assert!(block.contains("path = ~/.gitconfig-work"));
    }

    #[test]
    fn nested_folders_are_emitted_after_their_parents() {
        // Git applies includes in order and the last write wins, so the more
        // specific folder has to come second to override the broader one.
        let block = render_block(&[
            profile("client", &["~/code/work/client-x"]),
            profile("work", &["~/code/work"]),
        ]);
        let parent = block.find("gitdir:~/code/work/\"").unwrap();
        let child = block.find("gitdir:~/code/work/client-x/").unwrap();
        assert!(parent < child, "parent folder must be listed first");
    }

    #[test]
    fn include_file_quotes_values() {
        let mut p = profile("work", &[]);
        p.name = r#"A "Quoted" Name"#.into();
        let rendered = render_include_file(&p);
        assert!(rendered.contains(r#"name = "A \"Quoted\" Name""#));
        assert!(rendered.contains(r#"email = "work@example.com""#));
        assert!(rendered.contains("IdentitiesOnly=yes"));
    }

    #[test]
    fn profiles_without_folders_produce_no_includes() {
        assert_eq!(render_block(&[profile("work", &[])]), "");
    }
}
